images:
	@python3 src/extract_video_frames.py

detect-faces:
	@python3 src/extract_faces.py

recognize-faces:
	@python3 src/face_recognition_cnn.py	

install-dependencies:
	pip install opencv-python

reduce-dataset:
	@python3 src/reduce_data.py